[build-system]
requires = [
  "setuptools >= 43",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
target_version = ["py37"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.eggs
  | \.mypy_cache
  | \.tox
  | venv
  | _build
  | build
  | dist
  | docs
)/
'''
